#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd -m -1 &
pulseaudio &
nm-applet &

hsetroot -solid "#3b3b4d"

bspc monitor -d 1 2 3 4 5

bspc config window_gap 8
bspc config border_width 1

bspc config active_border_color "#44495E"
bspc config normal_border_color "#44495E"

bspc config split_ratio 0.5
